### ISSUE TITLE
Example doesn't work with latest version

### ISSUE THREAD

**Issue by MumblesNZ** [mimani/mongoose-diff-history#34]
To reproduce, update the version in /example/package.json to "mongoose-diff-history": "1.5.3" and run the app node server. 

You get the following error when trying to search for history: TypeError: History.find(...).lean(...).cursor is not a function.

Also the documentation for the GET/PUT requests in the README file need updating to include the employees path, i.e. localhost:3000/employees/:employeeId.

`TypeError: History.find(...).lean(...).cursor is not a function
    at Object.getHistories (C:\Users\..\Downloads\mongoose-diff-history-master\mongoose-diff-history-master\example\node_modules\mongoose-diff-history\diffHistory.js:125:10)
    at C:\Users\..\Downloads\mongoose-diff-history-master\mongoose-diff-history-master\example\routes\employees.js:149:21
    at Query.<anonymous> (C:\Users\..\Downloads\mongoose-diff-history-master\mongoose-diff-history-master\example\node_modules\mongoose\lib\query.js:2149:28)
    at C:\Users\..\Downloads\mongoose-diff-history-master\mongoose-diff-history-master\example\node_modules\kareem\index.js:177:19
    at C:\Users\..\Downloads\mongoose-diff-history-master\mongoose-diff-history-master\example\node_modules\kareem\index.js:109:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by mimani** [comment]
This should got fixed in latest version: 1.6, Kindly check.
