### ISSUE TITLE
findOneAndUpdate with upsert: true - throws exception with version 1.6

### ISSUE THREAD

**Issue by dhwpong** [mimani/mongoose-diff-history#39]
after upgrading to version 1.6 if upsert:true will throw the following exception
```
 /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: The given operator "$setOnInsert" is not implemented yet.
    at Function.assignUpdateOperation (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/power-assign/dist/power-assign.js:122:21)
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/power-assign/dist/power-assign.js:535:24
    at Array.reduce (<anonymous>)
    at assign (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/power-assign/dist/power-assign.js:534:15)
    at saveDiffHistory (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose-diff-history/diffHistory.js:84:5)
    at queryObject.find.lean.cursor.eachAsync.result (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose-diff-history/diffHistory.js:95:30)
    at handleNextResult (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/helpers/cursor/eachAsync.js:28:21)
    at Object.callback (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/helpers/cursor/eachAsync.js:53:9)
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/node_modules/async/dist/async.js:2271:31
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/node_modules/async/dist/async.js:969:16
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/helpers/cursor/eachAsync.js:45:9
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/cursor/QueryCursor.js:327:5
    at model.Document.init (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/document.js:437:5)
    at _create (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/cursor/QueryCursor.js:323:12)
    at /Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongoose/lib/cursor/QueryCursor.js:278:11
    at result (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb/lib/operations/cursor_ops.js:195:5)
    at handleCallback (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb-core/lib/cursor.js:204:5)
    at nextFunction (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb-core/lib/cursor.js:585:5)
    at done (/Users/cpphwp/dev/snpisd/ecrs-backend/node_modules/mongodb-core/lib/cursor.js:651:7)

```
error coming from "assign(dbObject, queryObject._update)," ?

try it with mongoose "mongoose": "^4.13.18" and "mongoose": "^5.4.17"
rolling back to "mongoose-diff-history": "^1.5.3 - the program works

**Comment by mimani** [comment]
@zjr Will it be possible for you to have a look at it sometime?

**Comment by dhwpong** [comment]
FYI - power-assign don't support $setOnInsert
(but since we don't need for insert query to be in the history, I think we can exclude the $setOnInsert) and do something like this?

const saveDiffHistory = (queryObject, currentObject, opts) => {
  const update = JSON.parse(JSON.stringify(queryObject._update));
  /* eslint-disable security/detect-object-injection */
  const updateParams = Object.assign(...Object.keys(update).map(function(key) {
    if(typeof update[key] === "object") {
      return update[key];
    }
    return update;
  }));
  /* eslint-enable security/detect-object-injection */
  const dbObject = pick(currentObject, Object.keys(updateParams));
  // method 1
  const _update = { ...queryObject._update };
  delete(_update.$setOnInsert);
  // method 2
  // const {['$setOnInsert']: deletedKey, ..._update } = queryObject._update;
  return saveDiffObject(
    currentObject,
    dbObject,
    assign(dbObject, _update),
    opts,
    queryObject
  );
};

**Comment by mimani** [comment]
Thanks for your contribution, I have published new version with your changes, with those, You issue shall be resolved. 

Thanks for using this library and fixing the issue you faced.

It will be really helpful if you can provide your use-case for which you are using this library, if it possible/allowed at your end, which can be put in the users section in ReadMe for this library. Having examples of real-life usage will give more confidence to future users of this library. Thanks.

**Comment by dhwpong** [comment]
Thanks for the quick turn around.  My project uses it for as logging changes of cases.

**Comment by zjr** [comment]
@mimani thanks for handling that & sorry I didn't manage to get to it (I'm in the middle of moving house right now and won't have spare time for a while yet).
